//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.UserWebServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserWebServiceReference.UserWebServiceSoap")]
    public interface UserWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAllEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ViewAllEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAllEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ViewAllEventsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserPurchasedTickets", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserPurchasedTickets(string userEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserPurchasedTickets", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserPurchasedTicketsAsync(string userEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserByEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateUserByEmail(string email, string name, string address, string contactNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserByEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateUserByEmailAsync(string email, string name, string address, string contactNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserWebServiceSoapChannel : DesktopApplication.UserWebServiceReference.UserWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserWebServiceSoapClient : System.ServiceModel.ClientBase<DesktopApplication.UserWebServiceReference.UserWebServiceSoap>, DesktopApplication.UserWebServiceReference.UserWebServiceSoap {
        
        public UserWebServiceSoapClient() {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ViewAllEvents() {
            return base.Channel.ViewAllEvents();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ViewAllEventsAsync() {
            return base.Channel.ViewAllEventsAsync();
        }
        
        public System.Data.DataSet GetUserPurchasedTickets(string userEmail) {
            return base.Channel.GetUserPurchasedTickets(userEmail);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserPurchasedTicketsAsync(string userEmail) {
            return base.Channel.GetUserPurchasedTicketsAsync(userEmail);
        }
        
        public System.Data.DataSet GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public bool UpdateUserByEmail(string email, string name, string address, string contactNo) {
            return base.Channel.UpdateUserByEmail(email, name, address, contactNo);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserByEmailAsync(string email, string name, string address, string contactNo) {
            return base.Channel.UpdateUserByEmailAsync(email, name, address, contactNo);
        }
    }
}
