//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.RegistrationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationServiceReference.RegistrationWebServiceSoap")]
    public interface RegistrationWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        WebApplication1.RegistrationServiceReference.RegisterUserResponse RegisterUser(WebApplication1.RegistrationServiceReference.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.RegistrationServiceReference.RegisterUserResponse> RegisterUserAsync(WebApplication1.RegistrationServiceReference.RegisterUserRequest request);
        
        // CODEGEN: Generating message contract since element name companyName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterPartner", ReplyAction="*")]
        WebApplication1.RegistrationServiceReference.RegisterPartnerResponse RegisterPartner(WebApplication1.RegistrationServiceReference.RegisterPartnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterPartner", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.RegistrationServiceReference.RegisterPartnerResponse> RegisterPartnerAsync(WebApplication1.RegistrationServiceReference.RegisterPartnerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUser", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.RegistrationServiceReference.RegisterUserRequestBody Body;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(WebApplication1.RegistrationServiceReference.RegisterUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contactNo;
        
        public RegisterUserRequestBody() {
        }
        
        public RegisterUserRequestBody(string name, string email, string password, string address, string contactNo) {
            this.name = name;
            this.email = email;
            this.password = password;
            this.address = address;
            this.contactNo = contactNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.RegistrationServiceReference.RegisterUserResponseBody Body;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(WebApplication1.RegistrationServiceReference.RegisterUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterUserResult;
        
        public RegisterUserResponseBody() {
        }
        
        public RegisterUserResponseBody(string RegisterUserResult) {
            this.RegisterUserResult = RegisterUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPartnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPartner", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.RegistrationServiceReference.RegisterPartnerRequestBody Body;
        
        public RegisterPartnerRequest() {
        }
        
        public RegisterPartnerRequest(WebApplication1.RegistrationServiceReference.RegisterPartnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterPartnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string companyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contactNo;
        
        public RegisterPartnerRequestBody() {
        }
        
        public RegisterPartnerRequestBody(string companyName, string email, string password, string address, string contactNo) {
            this.companyName = companyName;
            this.email = email;
            this.password = password;
            this.address = address;
            this.contactNo = contactNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPartnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPartnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.RegistrationServiceReference.RegisterPartnerResponseBody Body;
        
        public RegisterPartnerResponse() {
        }
        
        public RegisterPartnerResponse(WebApplication1.RegistrationServiceReference.RegisterPartnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterPartnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterPartnerResult;
        
        public RegisterPartnerResponseBody() {
        }
        
        public RegisterPartnerResponseBody(string RegisterPartnerResult) {
            this.RegisterPartnerResult = RegisterPartnerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrationWebServiceSoapChannel : WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationWebServiceSoapClient : System.ServiceModel.ClientBase<WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap>, WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap {
        
        public RegistrationWebServiceSoapClient() {
        }
        
        public RegistrationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.RegistrationServiceReference.RegisterUserResponse WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap.RegisterUser(WebApplication1.RegistrationServiceReference.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public string RegisterUser(string name, string email, string password, string address, string contactNo) {
            WebApplication1.RegistrationServiceReference.RegisterUserRequest inValue = new WebApplication1.RegistrationServiceReference.RegisterUserRequest();
            inValue.Body = new WebApplication1.RegistrationServiceReference.RegisterUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.address = address;
            inValue.Body.contactNo = contactNo;
            WebApplication1.RegistrationServiceReference.RegisterUserResponse retVal = ((WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap)(this)).RegisterUser(inValue);
            return retVal.Body.RegisterUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.RegistrationServiceReference.RegisterUserResponse> WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap.RegisterUserAsync(WebApplication1.RegistrationServiceReference.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.RegistrationServiceReference.RegisterUserResponse> RegisterUserAsync(string name, string email, string password, string address, string contactNo) {
            WebApplication1.RegistrationServiceReference.RegisterUserRequest inValue = new WebApplication1.RegistrationServiceReference.RegisterUserRequest();
            inValue.Body = new WebApplication1.RegistrationServiceReference.RegisterUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.address = address;
            inValue.Body.contactNo = contactNo;
            return ((WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap)(this)).RegisterUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.RegistrationServiceReference.RegisterPartnerResponse WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap.RegisterPartner(WebApplication1.RegistrationServiceReference.RegisterPartnerRequest request) {
            return base.Channel.RegisterPartner(request);
        }
        
        public string RegisterPartner(string companyName, string email, string password, string address, string contactNo) {
            WebApplication1.RegistrationServiceReference.RegisterPartnerRequest inValue = new WebApplication1.RegistrationServiceReference.RegisterPartnerRequest();
            inValue.Body = new WebApplication1.RegistrationServiceReference.RegisterPartnerRequestBody();
            inValue.Body.companyName = companyName;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.address = address;
            inValue.Body.contactNo = contactNo;
            WebApplication1.RegistrationServiceReference.RegisterPartnerResponse retVal = ((WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap)(this)).RegisterPartner(inValue);
            return retVal.Body.RegisterPartnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.RegistrationServiceReference.RegisterPartnerResponse> WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap.RegisterPartnerAsync(WebApplication1.RegistrationServiceReference.RegisterPartnerRequest request) {
            return base.Channel.RegisterPartnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.RegistrationServiceReference.RegisterPartnerResponse> RegisterPartnerAsync(string companyName, string email, string password, string address, string contactNo) {
            WebApplication1.RegistrationServiceReference.RegisterPartnerRequest inValue = new WebApplication1.RegistrationServiceReference.RegisterPartnerRequest();
            inValue.Body = new WebApplication1.RegistrationServiceReference.RegisterPartnerRequestBody();
            inValue.Body.companyName = companyName;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.address = address;
            inValue.Body.contactNo = contactNo;
            return ((WebApplication1.RegistrationServiceReference.RegistrationWebServiceSoap)(this)).RegisterPartnerAsync(inValue);
        }
    }
}
