//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.RegistrationWebServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistrationWebServiceReference.RegistrationWebServiceSoap")]
    public interface RegistrationWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        DesktopApplication.RegistrationWebServiceReference.RegisterUserResponse RegisterUser(DesktopApplication.RegistrationWebServiceReference.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApplication.RegistrationWebServiceReference.RegisterUserResponse> RegisterUserAsync(DesktopApplication.RegistrationWebServiceReference.RegisterUserRequest request);
        
        // CODEGEN: Generating message contract since element name companyName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterPartner", ReplyAction="*")]
        DesktopApplication.RegistrationWebServiceReference.RegisterPartnerResponse RegisterPartner(DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterPartner", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApplication.RegistrationWebServiceReference.RegisterPartnerResponse> RegisterPartnerAsync(DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUser", Namespace="http://tempuri.org/", Order=0)]
        public DesktopApplication.RegistrationWebServiceReference.RegisterUserRequestBody Body;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(DesktopApplication.RegistrationWebServiceReference.RegisterUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contactNo;
        
        public RegisterUserRequestBody() {
        }
        
        public RegisterUserRequestBody(string name, string email, string password, string address, string contactNo) {
            this.name = name;
            this.email = email;
            this.password = password;
            this.address = address;
            this.contactNo = contactNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public DesktopApplication.RegistrationWebServiceReference.RegisterUserResponseBody Body;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(DesktopApplication.RegistrationWebServiceReference.RegisterUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterUserResult;
        
        public RegisterUserResponseBody() {
        }
        
        public RegisterUserResponseBody(string RegisterUserResult) {
            this.RegisterUserResult = RegisterUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPartnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPartner", Namespace="http://tempuri.org/", Order=0)]
        public DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequestBody Body;
        
        public RegisterPartnerRequest() {
        }
        
        public RegisterPartnerRequest(DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterPartnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string companyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contactNo;
        
        public RegisterPartnerRequestBody() {
        }
        
        public RegisterPartnerRequestBody(string companyName, string email, string password, string address, string contactNo) {
            this.companyName = companyName;
            this.email = email;
            this.password = password;
            this.address = address;
            this.contactNo = contactNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterPartnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterPartnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public DesktopApplication.RegistrationWebServiceReference.RegisterPartnerResponseBody Body;
        
        public RegisterPartnerResponse() {
        }
        
        public RegisterPartnerResponse(DesktopApplication.RegistrationWebServiceReference.RegisterPartnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterPartnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterPartnerResult;
        
        public RegisterPartnerResponseBody() {
        }
        
        public RegisterPartnerResponseBody(string RegisterPartnerResult) {
            this.RegisterPartnerResult = RegisterPartnerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistrationWebServiceSoapChannel : DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationWebServiceSoapClient : System.ServiceModel.ClientBase<DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap>, DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap {
        
        public RegistrationWebServiceSoapClient() {
        }
        
        public RegistrationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApplication.RegistrationWebServiceReference.RegisterUserResponse DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap.RegisterUser(DesktopApplication.RegistrationWebServiceReference.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public string RegisterUser(string name, string email, string password, string address, string contactNo) {
            DesktopApplication.RegistrationWebServiceReference.RegisterUserRequest inValue = new DesktopApplication.RegistrationWebServiceReference.RegisterUserRequest();
            inValue.Body = new DesktopApplication.RegistrationWebServiceReference.RegisterUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.address = address;
            inValue.Body.contactNo = contactNo;
            DesktopApplication.RegistrationWebServiceReference.RegisterUserResponse retVal = ((DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap)(this)).RegisterUser(inValue);
            return retVal.Body.RegisterUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApplication.RegistrationWebServiceReference.RegisterUserResponse> DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap.RegisterUserAsync(DesktopApplication.RegistrationWebServiceReference.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApplication.RegistrationWebServiceReference.RegisterUserResponse> RegisterUserAsync(string name, string email, string password, string address, string contactNo) {
            DesktopApplication.RegistrationWebServiceReference.RegisterUserRequest inValue = new DesktopApplication.RegistrationWebServiceReference.RegisterUserRequest();
            inValue.Body = new DesktopApplication.RegistrationWebServiceReference.RegisterUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.address = address;
            inValue.Body.contactNo = contactNo;
            return ((DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap)(this)).RegisterUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApplication.RegistrationWebServiceReference.RegisterPartnerResponse DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap.RegisterPartner(DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequest request) {
            return base.Channel.RegisterPartner(request);
        }
        
        public string RegisterPartner(string companyName, string email, string password, string address, string contactNo) {
            DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequest inValue = new DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequest();
            inValue.Body = new DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequestBody();
            inValue.Body.companyName = companyName;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.address = address;
            inValue.Body.contactNo = contactNo;
            DesktopApplication.RegistrationWebServiceReference.RegisterPartnerResponse retVal = ((DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap)(this)).RegisterPartner(inValue);
            return retVal.Body.RegisterPartnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApplication.RegistrationWebServiceReference.RegisterPartnerResponse> DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap.RegisterPartnerAsync(DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequest request) {
            return base.Channel.RegisterPartnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApplication.RegistrationWebServiceReference.RegisterPartnerResponse> RegisterPartnerAsync(string companyName, string email, string password, string address, string contactNo) {
            DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequest inValue = new DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequest();
            inValue.Body = new DesktopApplication.RegistrationWebServiceReference.RegisterPartnerRequestBody();
            inValue.Body.companyName = companyName;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.address = address;
            inValue.Body.contactNo = contactNo;
            return ((DesktopApplication.RegistrationWebServiceReference.RegistrationWebServiceSoap)(this)).RegisterPartnerAsync(inValue);
        }
    }
}
