//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.UserWebServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserWebServiceReference.UserWebServiceSoap")]
    public interface UserWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAllEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ViewAllEvents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ViewAllEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ViewAllEventsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserWebServiceSoapChannel : WebApplication1.UserWebServiceReference.UserWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserWebServiceSoapClient : System.ServiceModel.ClientBase<WebApplication1.UserWebServiceReference.UserWebServiceSoap>, WebApplication1.UserWebServiceReference.UserWebServiceSoap {
        
        public UserWebServiceSoapClient() {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ViewAllEvents() {
            return base.Channel.ViewAllEvents();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ViewAllEventsAsync() {
            return base.Channel.ViewAllEventsAsync();
        }
    }
}
